# Generated by Django 4.0.1 on 2022-01-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',#model_name
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.TextField()),
                ('department', models.TextField()),
            ],
            options={
                'db_table': 'students',#table name
            },
        ),
    ]
